### ISSUE TITLE
feat: Create Contact Us Page

### ISSUE THREAD

**Issue by faculedesma** [Los-pica/project-first#9]
Create `ContactUs` page component. All links references can be found in https://tripsit.me

![Contact Us - Desktop](https://user-images.githubusercontent.com/27069195/199771806-c6c14a57-2e04-4c8b-b1ac-c086df5e8f60.png)

**Comment by WENCHO22** [comment]
los componentes serian:
-titulo
-parrafo
-link
?

**Comment by WENCHO22** [comment]
o el contact us(titulo) y el parrafo serian parte de un mismo componente?

**Comment by WENCHO22** [comment]
y para los links se podria reutilizar el componente link que hicimos para el header??
